FROM node:22-alpine AS base

RUN apk add --no-cache dumb-init

FROM base AS deps
RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json yarn.lock* package-lock.json* ./
RUN npm install

FROM base AS builder

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

COPY --from=builder --chown=nextjs:nodejs /app/start.sh ./start.sh
RUN chmod +x start.sh
RUN chown nextjs:nodejs start.sh

COPY --from=builder --chown=nextjs:nodejs /app/jobs.sh ./jobs.sh
RUN chmod +x jobs.sh
RUN chown nextjs:nodejs jobs.sh

# for migrations and seed
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src/lib ./src/lib
COPY --from=builder /app/src/db.ts ./src/db.ts
COPY --from=builder /app/src/db ./src/db
COPY --from=builder /app/package.json ./
COPY --from=builder /app/tsconfig.json ./
COPY --from=builder /app/drizzle.config.ts ./
COPY --from=builder /app/src/config.ts ./src/config.ts

# for any data generated by the application
# ./data should be persistent across deployments
RUN mkdir -p data
RUN chown nextjs:nodejs data

USER nextjs

EXPOSE 3000

ENV PORT=3000 HOSTNAME="0.0.0.0" NODE_ENV=production

CMD ["/usr/bin/dumb-init", "--", "/bin/sh", "/app/start.sh"]
